spring:
  application:
    name: bry-java-backend-challenge

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

challenge:
  document: resources/arquivos/doc.txt
  output-directory: artifacts
